apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2023"
  name: trekktabell-2023
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2023"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2023"
    spec:
      containers:
        - image: quay.twingine.com/asgeir/trekktabell:2023
          imagePullPolicy: Always
          name: trekktabell
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: asgeir-k8s-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2024"
  name: trekktabell-2024
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2024"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2024"
    spec:
      containers:
        - image: quay.twingine.com/asgeir/trekktabell:2024
          imagePullPolicy: Always
          name: trekktabell
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: asgeir-k8s-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2025"
  name: trekktabell-2025
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2025"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2025"
    spec:
      containers:
        - image: quay.twingine.com/asgeir/trekktabell:2025
          imagePullPolicy: Always
          name: trekktabell
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: asgeir-k8s-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2023"
  name: trekktabell-2023
  namespace: trekktabell
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    trekktabell: "2023"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2024"
  name: trekktabell-2024
  namespace: trekktabell
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    trekktabell: "2024"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2025"
  name: trekktabell-2025
  namespace: trekktabell
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    trekktabell: "2025"
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
  name: trekktabell
  namespace: trekktabell
spec:
  ingressClassName: nginx
  rules:
    - host: trekktabell.twingine.com
      http:
        paths:
          - backend:
              service:
                name: trekktabell-2023
                port:
                  number: 8080
            path: /2023
            pathType: Exact
          - backend:
              service:
                name: trekktabell-2024
                port:
                  number: 8080
            path: /2024
            pathType: Exact
          - backend:
              service:
                name: trekktabell-2025
                port:
                  number: 8080
            path: /2025
            pathType: Exact
  tls:
    - hosts:
        - trekktabell.twingine.com
      secretName: trekktabell-tls
