apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2023"
  name: trekktabell-2023
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2023"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2023"
    spec:
      containers:
      - image: zot.twingine.com/ghcr/asgeirn/trekktabell:2023@sha256:03ff678455449c1ca81348ba1b4529b1089ff82b68d0c92e3c9f421ff245a7e2
        imagePullPolicy: Always
        name: trekktabell
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2024"
  name: trekktabell-2024
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2024"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2024"
    spec:
      containers:
      - image: zot.twingine.com/ghcr/asgeirn/trekktabell:2024@sha256:5b9810d8340ff37faf61cab2adc9f618786622b2bd6483f3532bb15ee6f913a9
        imagePullPolicy: Always
        name: trekktabell
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    trekktabell: "2025"
  name: trekktabell-2025
  namespace: trekktabell
spec:
  replicas: 1
  selector:
    matchLabels:
      trekktabell: "2025"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        trekktabell: "2025"
    spec:
      containers:
      - image: zot.twingine.com/ghcr/asgeirn/trekktabell:2025@sha256:7eeae0b35a81c826d8f42cf0b5e24010290bf87b066f3337762fde4c2ffc909e
        imagePullPolicy: Always
        name: trekktabell
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2023"
  name: trekktabell-2023
  namespace: trekktabell
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    trekktabell: "2023"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2024"
  name: trekktabell-2024
  namespace: trekktabell
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    trekktabell: "2024"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    trekktabell: "2025"
  name: trekktabell-2025
  namespace: trekktabell
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    trekktabell: "2025"
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trekktabell
  namespace: trekktabell
spec:
  parentRefs:
  - name: gateway
    namespace: kgateway-system
  hostnames:
  - trekktabell.twingine.com
  rules:
  - matches:
    - path:
        type: Exact
        value: /2023
    backendRefs:
    - name: trekktabell-2023
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /2024
    backendRefs:
    - name: trekktabell-2024
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /2025
    backendRefs:
    - name: trekktabell-2025
      port: 8080
