steps:
  - label: ":maven: Build"
    command:
      - "mvn -B package --file pom.xml"
    plugins:
      - docker#v5.12.0:
          image: "maven:3-openjdk-17-slim"
    artifact_paths:
      - "target/bom.json"

  # TODO: Implement SecObserve SBOM upload once API details are confirmed
  # - label: ":shield: Upload SBOM"
  #   depends_on: "build"
  #   command:
  #     - "curl -X POST ..."
